import { LinkType } from '@/utils';

export const infoData = [
  {
    name: '我的订单',
    list: [
      // {
      //   url: `/packageA/pages/order/orderList/orderList?feedStatus=${ORDER_STATUS.PENDING_PAID}`,
      //   icon: require('@/static/icon/to-paid.png'),
      //   name: '待付款',
      //   type: LinkType.path,
      //   redDot: false,
      // },
      // {
      //   url: `/packageA/pages/order/orderList/orderList?feedStatus=${ORDER_STATUS.PENDING_SHIPMENT}`,
      //   icon: require('@/static/icon/to-ship.png'),
      //   name: '待发货',
      //   type: LinkType.path,
      //   redDot: false,
      // },
      // {
      //   url: `/packageA/pages/order/orderList/orderList?feedStatus=${ORDER_STATUS.PENDING_RECEIPT}`,
      //   icon: require('@/static/icon/to-received.png'),
      //   name: '待收货',
      //   type: LinkType.path,
      //   redDot: false,
      // },
      // {
      //   url: `/packageA/pages/order/orderList/orderList?feedStatus=${ORDER_STATUS.PENDING_COMMENT}`,
      //   icon: require('@/static/icon/finish.png'),
      //   name: '待评价',
      //   type: LinkType.path,
      //   redDot: false,
      // },
      // {
      //   url: `/packageA/pages/order/aftersales/aftersales`,
      //   icon: require('@/static/icon/after-sales.png'),
      //   name: '售后',
      //   type: LinkType.path,
      //   redDot: false,
      // },
    ],
  },
  {
    name: '我的服务',
    list: [
      {
        url: '/packageA/pages/signin/signin',
        icon: require('@/static/icon/sign.png'),
        name: '每日签到',
        type: LinkType.path,
        redDot: false,
      },
      // {
      //   url: '/packageA/pages/userInfo/userInfo',
      //   icon: require('@/static/icon/personal.png'),
      //   name: '个人信息',
      //   type: LinkType.path,
      //   redDot: false,
      // },
      // {
      //   url: '/packageA/pages/inviteFriends/inviteFriends',
      //   icon: require('@/static/icon/invite.png'),
      //   type: LinkType.path,
      //   name: '邀请好友',
      //   redDot: false,
      // },
      // {
      //   url: '/pages/shop/shop',
      //   icon: require('@/static/icon/gift.png'),
      //   type: LinkType.path,
      //   name: '浏览上新',
      //   redDot: false,
      // },
    ],
  },
  // {
  //   name: '我的服务',
  //   list: [
  //     {
  //       url: `/packageA/pages/newsGuide/newsGuide?title=${DOCUMENTS.XINSHOUGONGLUE.title}&code=${DOCUMENTS.XINSHOUGONGLUE.code}`,
  //       icon: require('@/static/icon/guide.png'),
  //       type: LinkType.path,
  //       name: '新手教程',
  //       redDot: false,
  //     },
  //     {
  //       url: '/packageA/pages/myFavorites/myFavorites',
  //       icon: require('@/static/icon/favrite.png'),
  //       type: LinkType.path,
  //       name: '我的收藏',
  //       redDot: false,
  //     },
  //     {
  //       url: '/packageA/pages/pointOrderList/pointOrderList',
  //       icon: require('@/static/icon/order.png'),
  //       type: LinkType.path,
  //       name: '积分订单',
  //       redDot: false,
  //     },
  //     {
  //       url: '/packageA/pages/coupon/couponList/couponList',
  //       icon: require('@/static/icon/coupon.png'),
  //       type: LinkType.path,
  //       name: '我的礼券',
  //       redDot: false,
  //     },
  //     {
  //       url: '/packageA/pages/memberRights/memberRights',
  //       icon: require('@/static/icon/benefits.png'),
  //       type: LinkType.path,
  //       name: '会员权益',
  //       redDot: false,
  //     },
  //     {
  //       url: '/packageA/pages/noticeCenter/noticeCenter',
  //       icon: require('@/static/icon/information.png'),
  //       type: LinkType.path,
  //       name: '消息中心',
  //       redDot: false,
  //     },
  //     {
  //       url: `/packageA/pages/help/help?title=${DOCUMENTS.FULI.title}&code=${DOCUMENTS.FULI.code}`,
  //       icon: require('@/static/icon/welfare.png'),
  //       type: LinkType.path,
  //       name: '社群福利',
  //       redDot: false,
  //     },
  //     {
  //       url: `/packageA/pages/help/help?title=${DOCUMENTS.REMENHUODONG.title}&code=${DOCUMENTS.REMENHUODONG.code}`,
  //       icon: require('@/static/icon/activitie.png'),
  //       type: LinkType.path,
  //       name: '热门活动',
  //       redDot: false,
  //     },
  //     {
  //       url: `/packageA/pages/events/eventList/eventList`,
  //       icon: require('@/static/icon/activity.png'),
  //       type: LinkType.path,
  //       name: '活动列表',
  //       redDot: false,
  //     },
  //     {
  //       url: '',
  //       icon: require('@/static/icon/customer.png'),
  //       type: LinkType.none,
  //       name: '专属客服',
  //       redDot: false,
  //     },
  //     {
  //       url: '/packageA/pages/setting/setting',
  //       icon: require('@/static/icon/setting.png'),
  //       type: LinkType.path,
  //       name: '更多信息',
  //       redDot: false,
  //     },
  //   ],
  // },
];
